### ISSUE TITLE
Igloo Contests not working

### ISSUE THREAD

**Issue by tootyta** [titshacking/Luna#1]
Is it possible to add Igloo Contests to Luna? Like, it would send either the username to a table in the database, or a text file like Contest.txt... When you submit an igloo to the contest.

**Comment by titshacking** [comment]
Yes it is possible to add igloo contests but I never added the packets and the handlers, you can easily implement this, you just need to find out what the packet is and write a function to handle it. Simply take a look at the client and you will be able to figure it out :smile:

**Comment by tootyta** [comment]
Lol, I have no idea how to write a function to handle it by looking at the client. But I do know how to get the packets... But, there is no igloo contest open on Current CP. How would I get the packet?

**Comment by titshacking** [comment]
Resolved.
