### ISSUE TITLE
My Puffle / Games Color Issue

### ISSUE THREAD

**Issue by tootyta** [titshacking/Luna#3]
So when I play a Game such as Hydro Hopper, it's supposed to match my penguin color. Instead, every time it shows black. Same with the game PBL My Puffle. My puffle is always blue even when I walk a for example... Pink Puffle.

**Comment by titshacking** [comment]
Support and updates for Luna has been stopped long ago, kindly follow Shawn's Repository located here https://github.com/ShawnTD/Luna who will be working on Luna from here on.
